apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-init-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-init
  template:
    metadata:
      labels:
        app: nginx-init
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
      initContainers:
      - name: init-wait-service
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup myservice-check.default.svc.cluster.local; do echo waiting for myservice-check; sleep 2; done"]
